// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbVI95ztGdUHa4OWiqFNZ3f3oK44L7INM',
    appId: '1:8283318311:web:50f6f0673c77e488a6c602',
    messagingSenderId: '8283318311',
    projectId: 'syncare-c5822',
    authDomain: 'syncare-c5822.firebaseapp.com',
    storageBucket: 'syncare-c5822.firebasestorage.app',
    measurementId: 'G-37XXKR6LQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACA-G7Ir8ni6-tflUE2LTfLUZFK-s83ok',
    appId: '1:8283318311:android:665460654d719e21a6c602',
    messagingSenderId: '8283318311',
    projectId: 'syncare-c5822',
    storageBucket: 'syncare-c5822.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCioByrRfxlgs0WSp31UwsZBgLpxA1BHEk',
    appId: '1:8283318311:ios:67d2d2db79a89d32a6c602',
    messagingSenderId: '8283318311',
    projectId: 'syncare-c5822',
    storageBucket: 'syncare-c5822.firebasestorage.app',
    iosBundleId: 'com.example.syncare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCioByrRfxlgs0WSp31UwsZBgLpxA1BHEk',
    appId: '1:8283318311:ios:67d2d2db79a89d32a6c602',
    messagingSenderId: '8283318311',
    projectId: 'syncare-c5822',
    storageBucket: 'syncare-c5822.firebasestorage.app',
    iosBundleId: 'com.example.syncare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbVI95ztGdUHa4OWiqFNZ3f3oK44L7INM',
    appId: '1:8283318311:web:3918ff0d5c23c1dea6c602',
    messagingSenderId: '8283318311',
    projectId: 'syncare-c5822',
    authDomain: 'syncare-c5822.firebaseapp.com',
    storageBucket: 'syncare-c5822.firebasestorage.app',
    measurementId: 'G-VPHX0X1LSN',
  );
}
